version: '3.8'

services:
  traefik:
    image: traefik:v2.9
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik-public
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${TRAEFIK_CONFIG_DIR:-./traefik/config}/traefik.yml:/etc/traefik/traefik.yml:ro
      - ${TRAEFIK_CONFIG_DIR:-./traefik/config}/dynamic:/etc/traefik/dynamic:ro
      - ${TRAEFIK_DATA_DIR:-./traefik/data}/acme:/etc/traefik/acme
      - ${TRAEFIK_LOG_DIR:-./traefik/logs}:/var/log/traefik
    environment:
      - TZ=${TZ:-UTC}
    labels:
      - "traefik.enable=true"
      # Dashboard
      - "traefik.http.routers.traefik.rule=Host(`${TRAEFIK_DASHBOARD_HOST:-traefik.localhost}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
      # Middleware - Secure Headers, Auth, IP Whitelist
      - "traefik.http.routers.traefik.middlewares=secure-headers,dashboard-auth,admin-whitelist"
      # HTTP to HTTPS redirect
      - "traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

networks:
  traefik-public:
    name: traefik-public
    external: true
