# Traefik Static Configuration

global:
  checkNewVersion: true
  sendAnonymousUsage: false

# Enable the Dashboard
api:
  dashboard: true
  insecure: false  # We'll secure this with middleware

# Entry Points configuration
entryPoints:
  web:
    address: ":80"
    # Redirect to HTTPS
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt

# Configure Let's Encrypt
certificatesResolvers:
  letsencrypt:
    acme:
      email: "your-email@example.com"  # Replace with your email
      storage: "/etc/traefik/acme/acme.json"
      tlsChallenge: {}

# Configure Providers
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: "traefik-public"
  
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

# Configure Logs
log:
  level: "INFO"
  format: "common"

# Configure Access Logs
accessLog:
  format: "common"
  filePath: "/var/log/traefik/access.log"
  bufferingSize: 100

# Configure Metrics
metrics:
  prometheus:
    entryPoint: metrics
